#pragma config(Sensor, S3,     color,          sensorEV3_Color, modeEV3Color_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[motorB] = 30;
	motor[motorC] = 30;

	// Left turn
	while(SensorValue(color) != 2) {}

	motor[motorB] = 50;
	motor[motorC] = 0;
	wait1Msec(650);

	motor[motorB] = 30;
	motor[motorC] = 30;

	// Right turn
	while(SensorValue(color) != 4) {}

	motor[motorB] = 0;
	motor[motorC] = 50;
	wait1Msec(650);

	while(SensorValue(color) != 6) {}
	motor[motorB] = 30;
	motor[motorC] = 30;
	wait1Msec(1000);
}
