#pragma config(Sensor, S3,     reflectedValue, sensorEV3_Color, modeEV3Color_Reflected)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define THRESHOLD 50

task main()
{
	motor[motorB] = 30;
	motor[motorC] = 30;

	// Beep 1
	while(SensorValue(reflectedValue) > THRESHOLD) {}

	motor[motorB] = 30;
	motor[motorC] = 30;
	playSound(soundBeepBeep);
	wait1Msec(1000);

	// Beep 2
	while(SensorValue(reflectedValue) > THRESHOLD) {}

	motor[motorB] = 30;
	motor[motorC] = 30;
	playSound(soundBeepBeep);
	wait1Msec(1000);
	playSound(soundBeepBeep);
	wait1Msec(1000);

	// Beep 3
	while(SensorValue(reflectedValue) > THRESHOLD) {}

	motor[motorB] = 30;
	motor[motorC] = 30;
	playSound(soundBeepBeep);
	wait1Msec(1000);
	playSound(soundBeepBeep);
	wait1Msec(1000);
	playSound(soundBeepBeep);
	wait1Msec(1000);


	// Beep 4
	while(SensorValue(reflectedValue) > THRESHOLD) {}

	motor[motorB] = 0;
	motor[motorC] = 0;
	playSound(soundBeepBeep);
	wait1Msec(1000);
	playSound(soundBeepBeep);
	wait1Msec(1000);
	playSound(soundBeepBeep);
	wait1Msec(1000);
	playSound(soundBeepBeep);
	wait1Msec(1000);
}
