#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[motorB] = 50;
	motor[motorC] = 50;

	while (getTouchValue(touchSensor) == 0) {}

	motor[motorB] = -50;
	motor[motorC] = -50;
	wait1Msec(300);

	motor[motorB] = 50;
	motor[motorC] = 0;
	wait1Msec(850);

	/////////////////////////

	motor[motorB] = 50;
	motor[motorC] = 50;

	while (getTouchValue(touchSensor) == 0) {}

	motor[motorB] = -50;
	motor[motorC] = -50;
	wait1Msec(300);

	motor[motorB] = 0;
	motor[motorC] = 50;
	wait1Msec(850);

	/////////////////////////

	motor[motorB] = 50;
	motor[motorC] = 50;

	while (getTouchValue(touchSensor) == 0) {}

	motor[motorB] = -50;
	motor[motorC] = -50;
	wait1Msec(300);

	motor[motorB] = 0;
	motor[motorC] = 50;
	wait1Msec(850);

	/////////////////////////

	motor[motorB] = 50;
	motor[motorC] = 50;

	while (getTouchValue(touchSensor) == 0) {}

	motor[motorB] = -50;
	motor[motorC] = -50;
	wait1Msec(300);

	motor[motorB] = 50;
	motor[motorC] = 0;
	wait1Msec(850);


	motor[motorB] = 50;
	motor[motorC] = 50;

	while (getTouchValue(touchSensor) == 0) {}
}
